# -*- coding: utf-8 -*-
""".h5 to onnx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsr7ChQZ-bjmntcgwCWFaowPGQl0ULWr
"""

!pip install tf2onnx

import tensorflow as tf
import tf2onnx

import tensorflow as tf
import tf2onnx

# Đường dẫn tới file .h5 và file .onnx
h5_model_path = "/content/model_cifar10 (2).h5"  # Thay bằng đường dẫn tới file .h5 của bạn
onnx_model_path = "/content/model_cifar10.onnx"  # Đường dẫn lưu file .onnx sau khi chuyển đổi

# Tải mô hình từ file .h5
model = tf.keras.models.load_model(h5_model_path)

# Wrap the Sequential model in a Functional API model
input_tensor = tf.keras.Input(shape=model.input_shape[1:]) # Get input shape from loaded model
output_tensor = model(input_tensor)
functional_model = tf.keras.Model(inputs=input_tensor, outputs=output_tensor)


# Chuyển đổi sang định dạng ONNX
# Use the functional_model instead of the original model
spec = (tf.TensorSpec(functional_model.input_shape, tf.float32),)
onnx_model, _ = tf2onnx.convert.from_keras(functional_model, input_signature=spec)

# Lưu mô hình ONNX
with open(onnx_model_path, "wb") as f:
    f.write(onnx_model.SerializeToString())

print(f"Mô hình đã được chuyển đổi và lưu tại: {onnx_model_path}")